security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        grosman:
            entity:
                class: App\Entity\User
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: grosman
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: login
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_GOD: ROLE_ADMIN
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/account, roles: ROLE_USER }
